version: "3.8"

name: budget-manager

services:
  service:
    container_name: ${COMPOSE_PROJECT_NAME}-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6666:6666"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - mongodb
      - rabbitmq
  mongodb:
    container_name: ${COMPOSE_PROJECT_NAME}-mongodb
    image: mongo:6-jammy
    restart: unless-stopped
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=budget_manager
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange:3.11.28-management
    container_name: ${COMPOSE_PROJECT_NAME}-rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mongodb_data:
  rabbitmq_data:
