version: "3.8"

name: budget-manager

services:
  service:
    container_name: ${COMPOSE_PROJECT_NAME}-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - mongodb
      - rabbitmq
    env_file:
      - .env
  mongodb:
    container_name: ${COMPOSE_PROJECT_NAME}-mongodb
    image: mongo:6-jammy
    restart: unless-stopped
    ports:
      - "127.0.0.1:${SPRING_DATA_MONGODB_PORT}:27017"
    volumes:
      - mongodb_data:/data/db
    env_file:
      - .env
  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange:3.11.28-management
    container_name: ${COMPOSE_PROJECT_NAME}-rabbitmq
    ports:
      - "15672:15672"
      - "${SPRING_DATA_RABBITMQ_PORT}:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    env_file:
      - .env

volumes:
  mongodb_data:
  rabbitmq_data:
