server:
  port: ${SERVER_PORT:6666}

grpc:
  server:
    port: ${GRPC_SERVER_PORT:9595}
    security:
      enabled: false
  client:
    service:
      address: ${GRPC_SERVER_CLIENT_ADDRESS:localhost:9090}
      negotiation-type: plaintext

spring:
  application:
    name: repetition-service

  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST:mongodb}
      port: ${SPRING_DATA_MONGODB_PORT:27017}
      authentication-database: ${SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE:admin}
      database: ${SPRING_DATA_MONGODB_DATABASE:budget_manager}
      password: ${SPRING_DATA_MONGODB_PASSWORD:mongo}
      username: ${SPRING_DATA_MONGODB_USERNAME:mongo}

  rabbitmq:
    host: ${SPRING_DATA_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_DATA_RABBITMQ_PORT:5672}
    username: ${SPRING_DATA_RABBITMQ_USERNAME:rabbit}
    password: ${SPRING_DATA_RABBITMQ_PASSWORD:rabbit}
    task-queue: ${SPRING_DATA_RABBITMQ_TASK_QUEUE:task-queue}
    custom-exchange: ${SPRING_DATA_RABBITMQ_CUSTOM_EXCHANGE:delayed-exchange}